def build(bld):
	sources = bld.path.ant_glob("*.c")
	bld.shlib(
		source = sources,
		target = 'termbox',
		name = 'termbox_shared',
		vnum = bld.env.VERSION,
	)
	bld.stlib(
		source = sources,
		target = 'termbox',
		name = 'termbox_static',
		install_path = '${LIBDIR}',
	)
	bld.install_files('${PREFIX}/include', 'termbox.h')
	bld.recurse("demo")
